repos:
  - repo: https://github.com/johnnymorganz/stylua
    rev: v0.13.1
    hooks:
      - id: stylua-github

  - repo: https://github.com/lunarmodules/luacheck
    rev: v0.26.1
    hooks:
      - id: luacheck
